### ISSUE TITLE
experimentWrapper

### ISSUE THREAD

**Issue by epaule** [glennhickey/cactus2hal#6]
I do believe in
/scratch/progressiveCactus/submodules/cactus2hal/bin/cactus2hal.py

the cactus.progressive.experimentWrapper should be changed to cactus.shared.experimentWrapper to make it work with recent versions of Progressive Cactus

**Comment by epaule** [comment]
i saw you fixed it in the devlopment branch with 72678e20b074316e42ec9ad3587bc8caf6db3f83 , can you merge it into master, so ProgressiveCactus pulls a working version?

**Comment by joelarmstrong** [comment]
Hmm, progressiveCactus should be pulling 0c184519a8 (which is on the development branch) if the submodule functionality is working properly. Which commit was your repository pointing to? Sadly the master branch for most of our repositories is several years old and usually broken (not my idea).

I've merged development into master anyway, as it's silly that the master branch is completely broken.

**Comment by epaule** [comment]
I just did a clean checkout of Progressive Cactus and it pulls
in 0c184519a8669fa473c9731d4d1a2bb22124a998 (remotes/origin/development)

whereas the version i was running from pointed
to ae208616781db8c23c3777b92b556962cd361266 (heads/master)
guess I must have messed up my local repo somehow.
